### ISSUE TITLE
Adding additional external modules

### ISSUE THREAD

**Issue by Regan-Koopmans** [katharosada/splootcode#111]
I noticed that `python/packages` contains a wheel of the `requests`. Is the easiest way to add another external module to paste an additional wheel in this folder?

**Comment by katharosada** [comment]
Ah that's there because it's a custom requests module that I built (to delegate to browser fetch and make blocking requests) rather than the real `requests` module. That shouldn't be necessary for other modules that come from PyPI or are already built for WASM/pyodide.

You'd need to add a line or two in the webworker when setting up pyodide.

Add a line here: https://github.com/katharosada/splootcode/blob/main/packages/runtime-python/src/webworker.ts#L242

Something like this and it should be able to fetch from pypi:
```
await micropip.install('somepackage') 
```

Note that only pure python packages and packages supported by pyodide will work this way. 
See the pyodide docs for more info: https://pyodide.org/en/stable/usage/loading-packages.html

**Comment by Regan-Koopmans** [comment]
Ah great, thank you!
