### ISSUE TITLE
Tweaking color of tree connectors

### ISSUE THREAD

**Issue by kkeri** [katharosada/splootcode#6]
Hi, let me propose a small improvement in the code editor. The overall look of code is professional, but tree connections are a bit distracting to my eyes. I changed colors in the browser to test my idea and it was instantly easier to read through lines. It looks like this:

![splootcode](https://user-images.githubusercontent.com/1475458/108592480-51befd00-736e-11eb-8eb0-74e145341435.png)

I used `#414a57` and also adjusted the thickness of `.indented-rule` to `1.4px`.

Making always-present information less prominent also leaves more room for focused elements. What do you think?

**Comment by katharosada** [comment]
Thanks so much for the suggestion!

You're absolutely right that the tree connectors can be very distracting to the visual flow, and I've been trying to find the right balance for the node rectangles to make them visible but non-interrupting. I hadn't applied that to the connectors.

I'm a little worried that this change makes the labels unreadable though, perhaps I can make the connectors darker, but leave the connector labels using a lighter shade so the labels are still readable. Some of the changes that I'm working on at the moment (changing the format of variable assignment nodes, as well as list index accessors) rely more on the connector-labels than previously. I am considering removing the `set` keyword, so that the assignment expression is just the little 'set to' labeled connector that you see there. I would be interested in your thoughts on that change.

There's also the option of making the brackets a little smaller so they fit in more with the flow of each line and take up less space.

**Comment by kkeri** [comment]
One thing that came into mind when I tried out your code editor was that *set...set to* is a little redundant. So I guess why you are planning to change it. What is unclear to me is how do I enter a variable assignment? I assume people will keep learning JS in its conventional form. Writing `let x = 1` is straightforward. How does it translate to your environment? Which keys should I hit in order to input an assignment? Can I discover it myself?

I'm eager to know what use cases for connector labels you have in mind. I would say if you plan only three or four different labels, moderate readability may be enough. Users probably learn to identify them by their shape and context. Although if you plan a variety of different labels, readability is indeed a concern.
Although I would beware of overusing text. Symbols like an equality sign are visual anchors that allow one to pick variable assignments easily. (May be double line connectors for assignments? I don't know.)

Another disruptive idea if you don't mind. I noticed that right parens stack up at the end of lines. If it is always the case, are they really informative? I would even consider omitting them and changing left parens to vertical bars, little sockets or something else. (Btw, how do parentheses inside expressions should look like? Are they the same style or different?)
Okay, I stop before overwhelming you with my suggestions. But this is an ideal time for experimentation, I believe.

**Comment by katharosada** [comment]
Alrighty, I've had a bit of a play around with your suggestions!

I ended up going a shade lighter than you recommended, mostly because I have two monitors and the dark grays look much darker on one monitor than the other (so it got a bit harder to see than I was comfortable with).

Before pic:
![image](https://user-images.githubusercontent.com/4311392/109243096-6a2c8d00-7830-11eb-843b-914f53f79f7c.png)

After pic:
![image](https://user-images.githubusercontent.com/4311392/109243129-7ca6c680-7830-11eb-9afe-bb65f8e7b438.png)

It is much easier on the eyes and allows you to focus on the main text more easily. I like it! :)
I also separated the css variables for the connector labels so I could control them individually, the labels are also a slightly lighter than the connectors which makes them easier to read but still look like they're matching. They now also turn blue when the node is highlighted.

The main use case I have for connector labels going forward is to label parameters on function calls, like this:
![image](https://user-images.githubusercontent.com/4311392/109243380-ee7f1000-7830-11eb-801d-18821fc78670.png)
Currently it only works on built-in javascript functions and case where I can match the function to its definition, so it doesn't actually show up in my examples.

**Comment by katharosada** [comment]
Thank you so much for these suggestions! It's going to take me longer to work out the whole set and set-to business but I'll keep working on that. I do like the idea of using a bar or other UI indicator instead of a matched set of brackets when they're on the same line (and go back to brackets if the line gets long enough to wrap). I have a few mocks of this but for now I want to keep the implementation simple and leave that for a later UI tweak when I implement automatic wrapping.

As for assignment, I image it to work like ... you type the variable name (the variable block appears), then with the cursor to the right of the variable block, you could type "set" or "set to" and it would attach a connector with "set to" and brackets to the variable block, essentially wrapping that variable reference in an assignment expression. Still working on it, but it makes sense in my head. :)

**Comment by kkeri** [comment]
Thank you for considering my suggestions! The lighter shade of labels plays very well with connectors. Displaying parameter names is a great idea. I frequently rely on intellisense to recall function parameters, so this feature might be really helpful. I hope later it will be extended to packages too.

Actually, I have a few more UI improvement ideas. You will probably want to put them aside because they don't add immediate value, and some of them requires preparations in the codebase. Anyway, I would be happy to share them if you are interested.

I'd like to ask you whether Splootcode is complete enough so that I can write a simple application from scratch and run it? If (or when) it is, I'm ready to be a test user.
